INSERT INTO table_category (name, created_at) VALUES ('Computador', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Máquina de lavar', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Smartphone', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Teclado Gamer', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Notebook', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Computador', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Máquina de lavar', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Smartphone', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Teclado Gamer', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Notebook', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Computador', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Máquina de lavar', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Smartphone', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Teclado Gamer', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Notebook', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Computador', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Máquina de lavar', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Smartphone', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Teclado Gamer', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Notebook', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Computador', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Máquina de lavar', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Smartphone', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Teclado Gamer', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Notebook', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Computador', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Máquina de lavar', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Smartphone', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Teclado Gamer', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Notebook', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Computador', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Máquina de lavar', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Smartphone', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Teclado Gamer', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Notebook', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Computador', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Máquina de lavar', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Smartphone', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Teclado Gamer', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Notebook', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Computador', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Máquina de lavar', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Smartphone', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Teclado Gamer', NOW());
INSERT INTO table_category (name, created_at) VALUES ('Notebook', NOW());